### ISSUE TITLE
Error using animalcages_v2.0.2

### ISSUE THREAD

**Issue by Cybertaz05** [G3rste/animalcages#2]
Hi when i try to  catch a animal with a cage medium cage i think it is. i get thrown out of the server. 

My mod list
https://cdn.discordapp.com/attachments/886608127926104106/886608138604781628/unknown.png

The error message i get when I'm thrown out 
https://cdn.discordapp.com/attachments/886608127926104106/886609312959565854/unknown.png

Here is the server errors.
https://cdn.discordapp.com/attachments/886608127926104106/886609816045383740/unknown.png

I tried the medium cage on a ram.
and i tried to just left click it on the ram. and that error. and the same if i hurt it first with a sword.

Got another person to recreate it and he are having the same issues.

**Comment by G3rste** [comment]
Hi,
does it happen without the mods, too?
does it only happen with the medium cage or does it happen with the small cage too?

could you send me the contents of your animalcagesconfig.json?

**Comment by Cybertaz05** [comment]
[animalcagesconfig.zip](https://github.com/G3rste/animalcages/files/7154125/animalcagesconfig.zip)
I play on the Vintage Story version 1.15.5.
i havent tried with only that mod.
but my friend tried it with small cages and that worked.

it looks like it is a conflict yes. i disabled all mods exept the core ones for the game.  but i tried again and got the medium cage to work.  i still got a crash then and the log is here 
[crash.txt](https://github.com/G3rste/animalcages/files/7154310/crash.txt)

**Comment by G3rste** [comment]
I am sorry but i cant recreate your issue.
I have used the same mod-setup in my singleplayer world and caught a ram without any problems.

Do you have any other unusual settings?

If the problem persists, feel free to hit me up on discord: G3rste#1850

**Comment by G3rste** [comment]
The error seems to occur on some setups where the server and client installation is somewhat mixed (do not quote me on that tho).
The mod tries to load the VSEssentials.dll but can not do so because of some setup issue:
```
System.IO.FileNotFoundException: Could not load file or assembly 'VSEssentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'VSEssentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

I have found the same issue at https://www.gitmemory.com/JyeGuru

The WorkAround he provided was adding the VSEssentials.dll to the modpath-folder.
