### ISSUE TITLE
Big cage make exception on mp server

### ISSUE THREAD

**Issue by dann1kid** [G3rste/animalcages#5]
21.11.2021 22:03:59 [Error] System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "VSEssentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Имя файла: 'VSEssentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   в Animalcages.BlockMediumCage.isCatchable(Entity attackedEntity)
   в Animalcages.BlockCage.OnAttackingWith(IWorldAccessor world, Entity byEntity, Entity attackedEntity, ItemSlot itemslot) в c:\GSM\servers\8\serverfiles\data\Cache\unpack\animalcages_v2.0.2 (1).zip_ff3664438b4f\src\blockcage.cs:строка 38
   в **Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode)**
   в Vintagestory.Server.ServerSystemEntitySimulation.HandleEntityInteraction(_vkCtd3V2CRuLlQ7XyXjgNwLPQVG packet, ConnectedClient client)
   в Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket)

**Comment by G3rste** [comment]
You are using an older version of this mod, which sometimes caused this error. Please make sure to use [v2.0.3](https://mods.vintagestory.at/download?fileid=2761).

**Comment by G3rste** [comment]
Duplicate of #2
